version: '2.1'
services:

  mariadb:
    environment:
      - DATABASE=${DATABASE}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:build
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker_network
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  wordpress:
    environment:
      - TITLE=${TITLE}
      - DATABASE=${DATABASE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - HOSTNAME=${DB_HOSTNAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress:build
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - docker_network
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:build
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

networks:
  docker_network:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lebourre/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lebourre/data/wp
      o: bind
